apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-kustomize-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vinothkumar24091996/ArgoCD-Kustomize.git
    targetRevision: HEAD
    path: kustomize/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-kustomize-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
