apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grade-submission-api-deployment.yaml
  - grade-submission-api-service.yaml

images:
  - name: 254185428277.dkr.ecr.us-east-1.amazonaws.com/vinoth-kustomize
    newName: 254185428277.dkr.ecr.us-east-1.amazonaws.com/vinoth-kustomize
    newTag: latest
